#ifndef _DEFINES_GRAPHIC_H_
#define _DEFINES_GRAPHIC_H_

#include <lcom/lcf.h>

#define SECONDS_TO_MICROS 1000000

#define VBE_LINEAR_FRAME_BUFFER_MODEL BIT(14)
#define VBE_CALL_AH 0x4F
#define VBE_FUNCTION_SET_MODE 0x02
#define VBE_FUNCTION_AH_SUCCESS 0x00

#define BIOS_VIDEO_SERVICES 0x10



#endif /* _DEFINES_GRAPHIC_H */
